#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { basename, dirname, join, resolve } from 'path'
import { COMMAND_CENTER_ROOT } from './lib/project-paths.mjs'

const PROFILES_ROOT = join(COMMAND_CENTER_ROOT, 'profiles')
const SIBLING_TALKSTORE_ROOT = resolve(COMMAND_CENTER_ROOT, '..', 'talkstore')
const DEFAULT_ENV_PATH = join(COMMAND_CENTER_ROOT, '.env')
const PRIMARY_ENV_KEYS = [
  'COMMAND_CENTER_PROFILE',
  'COMMAND_CENTER_PROJECT_ROOT',
  'COMMAND_CENTER_TRACKER_FILE',
  'COMMAND_CENTER_TASKS_DOC',
  'COMMAND_CENTER_CHECKLIST_DOC',
  'COMMAND_CENTER_MANIFESTO_DOC',
]

function loadProfileManifest(profileId) {
  const manifestPath = join(PROFILES_ROOT, profileId, 'manifest.json')
  if (!existsSync(manifestPath)) {
    throw new Error(`Profile manifest not found for "${profileId}" at ${manifestPath}.`)
  }

  return JSON.parse(readFileSync(manifestPath, 'utf8'))
}

function parseArgs(argv) {
  const args = {
    project: null,
    profile: null,
    outputEnvFile: null,
    tracker: null,
    tasks: null,
    checklist: null,
    manifesto: null,
    help: false,
    unknown: [],
  }

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--project') args.project = argv[++i] || null
    else if (arg === '--profile') args.profile = argv[++i] || null
    else if (arg === '--output-env-file') args.outputEnvFile = argv[++i] || null
    else if (arg === '--tracker') args.tracker = argv[++i] || null
    else if (arg === '--tasks') args.tasks = argv[++i] || null
    else if (arg === '--checklist') args.checklist = argv[++i] || null
    else if (arg === '--manifesto') args.manifesto = argv[++i] || null
    else if (arg === '--help' || arg === '-h') args.help = true
    else args.unknown.push(arg)
  }

  return args
}

function parseEnv(content) {
  const values = new Map()
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const match = /^([A-Z0-9_]+)\s*=\s*(.*)$/.exec(trimmed)
    if (!match) continue
    values.set(match[1], match[2])
  }
  return values
}

function printHelp() {
  console.log(
    'Sha8al Command Center bootstrap (sha8al-command-center)\n' +
    '\n' +
    'Usage:\n' +
    '  npm run bootstrap -- --project <project-root> [options]\n' +
    '\n' +
    'Public-first example:\n' +
    '  npm run bootstrap -- --project ./examples/minimal-command-center-project\n' +
    '\n' +
    'Preview to a separate env file:\n' +
    '  npm run bootstrap -- --project /path/to/project --output-env-file /tmp/command-center.env\n' +
    '\n' +
    'TalkStore compatibility:\n' +
    '  npm run bootstrap -- --project ../talkstore --profile talkstore\n' +
    '\n' +
    'Options:\n' +
    '  --project <path>           Project root that owns the tracker and docs. Required.\n' +
    '  --profile <id>            Consumer profile. Defaults to generic unless TalkStore is inferred.\n' +
    '  --output-env-file <path>  Write the generated env file to a custom path instead of ./.env.\n' +
    '  --tracker <filename>      Override the tracker filename relative to the project root.\n' +
    '  --tasks <path>            Override the tasks document path.\n' +
    '  --checklist <path>        Override the checklist document path.\n' +
    '  --manifesto <path>        Override the manifesto document path.\n' +
    '  -h, --help                Show this help.\n' +
    '\n' +
    'Notes:\n' +
    '  Bootstrap writes COMMAND_CENTER_* keys for fresh external installs.\n' +
    '  TALKSTORE_PROJECT_ROOT is only written when the talkstore profile is selected for compatibility.\n'
  )
}

function buildEnvLines(existing, profile) {
  const generatedKeys = [
    ...PRIMARY_ENV_KEYS,
    ...(profile.id === 'talkstore' ? ['TALKSTORE_PROJECT_ROOT'] : []),
  ]
  const generatedKeySet = new Set(generatedKeys)
  const preservedEntries = Array.from(existing.entries()).filter(([key]) => !generatedKeySet.has(key))

  return [
    '# Generated by scripts/bootstrap.mjs',
    profile.id === 'talkstore'
      ? '# TalkStore compatibility bootstrap. COMMAND_CENTER_* remains the primary configuration surface.'
      : '# Public-first bootstrap for external Sha8al Command Center projects.',
    profile.id === 'talkstore'
      ? '# TALKSTORE_PROJECT_ROOT is included below for legacy compatibility only.'
      : '# Re-run bootstrap whenever you want to refresh these defaults.',
    '',
    ...generatedKeys
      .filter((key) => existing.has(key))
      .map((key) => `${key}=${existing.get(key)}`),
    ...(preservedEntries.length
      ? [
          '',
          '# Preserved existing keys from the previous env file.',
          ...preservedEntries.map(([key, value]) => `${key}=${value}`),
        ]
      : []),
    '',
  ]
}

const args = parseArgs(process.argv.slice(2))
const ENV_PATH = args.outputEnvFile ? resolve(args.outputEnvFile) : DEFAULT_ENV_PATH

if (args.help) {
  printHelp()
  process.exit(0)
}

if (args.unknown.length) {
  console.error(`Unknown option${args.unknown.length === 1 ? '' : 's'}: ${args.unknown.join(', ')}`)
  console.error('')
  printHelp()
  process.exit(1)
}

if (!args.project) {
  printHelp()
  process.exit(1)
}

function inferProfileId({ profile, project, tracker }) {
  if (profile) return profile
  if (process.env.COMMAND_CENTER_PROFILE) return process.env.COMMAND_CENTER_PROFILE
  if (tracker && basename(tracker) === 'talkstore-tracker.json') return 'talkstore'
  if (existsSync(join(resolve(project), 'talkstore-tracker.json'))) return 'talkstore'
  if (resolve(project) === SIBLING_TALKSTORE_ROOT) return 'talkstore'
  return 'generic'
}

function chooseTrackerFile(profile, projectRoot, explicitTracker) {
  if (explicitTracker) return explicitTracker

  const candidates = [
    profile.tracker.primary_filename,
    ...(profile.tracker.compatibility_filenames || []),
  ].filter(Boolean)

  for (const candidate of candidates) {
    if (existsSync(join(projectRoot, candidate))) return candidate
  }

  return profile.tracker.default_creation_filename || profile.tracker.primary_filename
}

const profileId = inferProfileId(args)
if (profileId !== 'generic' && profileId !== 'talkstore') {
  console.error(`Unknown consumer profile "${profileId}". Expected "generic" or "talkstore".`)
  process.exit(1)
}

const profile = loadProfileManifest(profileId)
const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : new Map()
const resolvedProjectRoot = resolve(args.project)
const trackerFile = chooseTrackerFile(profile, resolvedProjectRoot, args.tracker)

existing.set('COMMAND_CENTER_PROFILE', profile.id)
existing.set('COMMAND_CENTER_PROJECT_ROOT', resolvedProjectRoot)
existing.set('COMMAND_CENTER_TRACKER_FILE', trackerFile)
existing.set('COMMAND_CENTER_TASKS_DOC', args.tasks || profile.docs.tasks.default_path)
existing.set('COMMAND_CENTER_CHECKLIST_DOC', args.checklist || profile.docs.checklist.default_path)
existing.set('COMMAND_CENTER_MANIFESTO_DOC', args.manifesto || profile.docs.manifesto.default_path)

if (profile.id === 'talkstore') {
  existing.set('TALKSTORE_PROJECT_ROOT', resolvedProjectRoot)
} else {
  existing.delete('TALKSTORE_PROJECT_ROOT')
}

const lines = buildEnvLines(existing, profile)

mkdirSync(dirname(ENV_PATH), { recursive: true })
writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')

console.log(`Wrote ${ENV_PATH}`)
console.log(`Consumer profile: ${existing.get('COMMAND_CENTER_PROFILE')}`)
console.log(`Project root: ${existing.get('COMMAND_CENTER_PROJECT_ROOT')}`)
console.log(`Tracker file: ${existing.get('COMMAND_CENTER_TRACKER_FILE')}`)
console.log(`Tasks doc: ${existing.get('COMMAND_CENTER_TASKS_DOC')}`)
console.log(`Checklist doc: ${existing.get('COMMAND_CENTER_CHECKLIST_DOC')}`)
console.log(`Manifesto doc: ${existing.get('COMMAND_CENTER_MANIFESTO_DOC')}`)
console.log(
  profile.id === 'talkstore'
    ? 'Compatibility: TALKSTORE_PROJECT_ROOT was written for existing TalkStore installs.'
    : 'Compatibility: no TalkStore-specific env keys were written.'
)
console.log('')
console.log('Next steps:')
if (ENV_PATH === DEFAULT_ENV_PATH) {
  console.log('1. Review the generated .env if your project uses non-default file names.')
} else {
  console.log(`1. Review ${ENV_PATH} and move or source it for local use.`)
}
console.log('2. Run `npm run tracker:guard:status` before any tracker write.')
console.log(
  profile.id === 'talkstore'
    ? '3. Dry-run `npm run tracker:parse:talkstore-tasks:dry-run` before any compatibility write.'
    : '3. Dry-run `npm run tracker:parse:project-tasks:dry-run` before any tracker write.'
)
console.log(
  profile.id === 'talkstore'
    ? '4. Write only after the dry-run looks correct with `npm run tracker:parse:talkstore-tasks`.'
    : '4. Write only after the dry-run looks correct with `npm run tracker:parse:project-tasks`.'
)
