#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { basename, dirname, join, resolve } from 'path'
import { createInterface } from 'readline/promises'
import { scaffoldGenericStarterDocs } from './lib/bootstrap-scaffold.mjs'
import { COMMAND_CENTER_ROOT } from './lib/project-paths.mjs'

const PROFILES_ROOT = join(COMMAND_CENTER_ROOT, 'profiles')
const SIBLING_TALKSTORE_ROOT = resolve(COMMAND_CENTER_ROOT, '..', 'talkstore')
const DEFAULT_ENV_PATH = join(COMMAND_CENTER_ROOT, '.env')
const MANAGED_ENV_KEYS = [
  'COMMAND_CENTER_PROFILE',
  'COMMAND_CENTER_PROJECT_ROOT',
  'COMMAND_CENTER_TRACKER_FILE',
  'COMMAND_CENTER_TASKS_DOC',
  'COMMAND_CENTER_CHECKLIST_DOC',
  'COMMAND_CENTER_MANIFESTO_DOC',
  'TALKSTORE_PROJECT_ROOT',
]

function loadProfileManifest(profileId) {
  const manifestPath = join(PROFILES_ROOT, profileId, 'manifest.json')
  if (!existsSync(manifestPath)) {
    throw new Error(`Profile manifest not found for "${profileId}" at ${manifestPath}.`)
  }

  return JSON.parse(readFileSync(manifestPath, 'utf8'))
}

function parseArgs(argv) {
  const args = {
    project: null,
    profile: null,
    outputEnvFile: null,
    tracker: null,
    tasks: null,
    checklist: null,
    manifesto: null,
    help: false,
    unknown: [],
  }

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--project') args.project = argv[++i] || null
    else if (arg === '--profile') args.profile = argv[++i] || null
    else if (arg === '--output-env-file') args.outputEnvFile = argv[++i] || null
    else if (arg === '--tracker') args.tracker = argv[++i] || null
    else if (arg === '--tasks') args.tasks = argv[++i] || null
    else if (arg === '--checklist') args.checklist = argv[++i] || null
    else if (arg === '--manifesto') args.manifesto = argv[++i] || null
    else if (arg === '--help' || arg === '-h') args.help = true
    else args.unknown.push(arg)
  }

  return args
}

function parseEnv(content) {
  const values = new Map()
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const match = /^([A-Z0-9_]+)\s*=\s*(.*)$/.exec(trimmed)
    if (!match) continue
    values.set(match[1], match[2])
  }
  return values
}

function printHelp() {
  console.log(
    'Sha8al Command Center bootstrap (sha8al-command-center)\n' +
    '\n' +
    'Usage:\n' +
    '  npm run bootstrap -- --project <project-root> [options]\n' +
    '\n' +
    'Public-first example:\n' +
    '  npm run bootstrap -- --project ./examples/minimal-command-center-project\n' +
    '\n' +
    'Preview to a separate env file:\n' +
    '  npm run bootstrap -- --project /path/to/project --output-env-file /tmp/command-center.env\n' +
    '\n' +
    'TalkStore compatibility:\n' +
    '  npm run bootstrap -- --project ../talkstore --profile talkstore\n' +
    '\n' +
    'Options:\n' +
    '  --project <path>           Project root that owns the tracker and docs. Required.\n' +
    '  --profile <id>            Consumer profile. Defaults to generic unless TalkStore is inferred.\n' +
    '  --output-env-file <path>  Write the generated env file to a custom path instead of ./.env.\n' +
    '  --tracker <filename>      Override the tracker filename relative to the project root.\n' +
    '  --tasks <path>            Override the roadmap/task document path.\n' +
    '  --checklist <path>        Override the checklist document path.\n' +
    '  --manifesto <path>        Override the manifesto document path.\n' +
    '  -h, --help                Show this help.\n' +
    '\n' +
    'Notes:\n' +
    '  Bootstrap writes COMMAND_CENTER_* keys for fresh external installs.\n' +
    '  Public generic installs use docs/roadmap.md because it feeds the swim lane and task board.\n' +
    '  If docs/roadmap.md is missing, bootstrap scaffolds docs/roadmap.md and docs/manifesto.md.\n' +
    '  TALKSTORE_PROJECT_ROOT is only written when the talkstore profile is selected for compatibility.\n'
  )
}

function buildEnvLines(existing, profile, generatedKeys) {
  const generatedKeySet = new Set(MANAGED_ENV_KEYS)
  const preservedEntries = Array.from(existing.entries()).filter(([key]) => !generatedKeySet.has(key))

  return [
    '# Generated by scripts/bootstrap.mjs',
    profile.id === 'talkstore'
      ? '# TalkStore compatibility bootstrap. COMMAND_CENTER_* remains the primary configuration surface.'
      : '# Public-first bootstrap for external Sha8al Command Center projects.',
    profile.id === 'talkstore'
      ? '# TALKSTORE_PROJECT_ROOT is included below for legacy compatibility only.'
      : '# Re-run bootstrap whenever you want to refresh these defaults.',
    '',
    ...generatedKeys
      .filter((key) => existing.has(key))
      .map((key) => `${key}=${existing.get(key)}`),
    ...(preservedEntries.length
      ? [
          '',
          '# Preserved existing keys from the previous env file.',
          ...preservedEntries.map(([key, value]) => `${key}=${value}`),
        ]
      : []),
    '',
  ]
}

const args = parseArgs(process.argv.slice(2))
const ENV_PATH = args.outputEnvFile ? resolve(args.outputEnvFile) : DEFAULT_ENV_PATH

if (args.help) {
  printHelp()
  process.exit(0)
}

if (args.unknown.length) {
  console.error(`Unknown option${args.unknown.length === 1 ? '' : 's'}: ${args.unknown.join(', ')}`)
  console.error('')
  printHelp()
  process.exit(1)
}

if (!args.project) {
  printHelp()
  process.exit(1)
}

function inferProfileId({ profile, project, tracker }) {
  if (profile) return profile
  if (process.env.COMMAND_CENTER_PROFILE) return process.env.COMMAND_CENTER_PROFILE
  if (tracker && basename(tracker) === 'talkstore-tracker.json') return 'talkstore'
  if (existsSync(join(resolve(project), 'talkstore-tracker.json'))) return 'talkstore'
  if (resolve(project) === SIBLING_TALKSTORE_ROOT) return 'talkstore'
  return 'generic'
}

function chooseTrackerFile(profile, projectRoot, explicitTracker) {
  if (explicitTracker) return explicitTracker

  const candidates = [
    profile.tracker.primary_filename,
    ...(profile.tracker.compatibility_filenames || []),
  ].filter(Boolean)

  for (const candidate of candidates) {
    if (existsSync(join(projectRoot, candidate))) return candidate
  }

  return profile.tracker.default_creation_filename || profile.tracker.primary_filename
}

async function confirmRoadmapUsage(roadmapPath) {
  if (!process.stdin.isTTY || !process.stdout.isTTY) return true

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  try {
    const answer = await rl.question(
      `Detected ${roadmapPath}. Use this roadmap.md for the tracker-driven flow? [Y/n] `
    )
    const normalized = answer.trim().toLowerCase()
    return !normalized || normalized === 'y' || normalized === 'yes'
  } finally {
    rl.close()
  }
}

async function ensureGenericStarterDocs(projectRoot) {
  const scaffoldResult = scaffoldGenericStarterDocs(projectRoot)

  if (scaffoldResult.created.length > 0) {
    console.log('Scaffolded starter docs for the public generic flow:')
    for (const relativePath of scaffoldResult.created) {
      console.log(`- ${join(projectRoot, relativePath)}`)
    }
    console.log('Replace the starter roadmap tasks with your real milestone plan before serious build work.')
  }

  return scaffoldResult
}

async function validateGenericRoadmap(projectRoot, configuredTasksDoc, explicitTasksOverride) {
  const expectedRoadmapPath = join(projectRoot, 'docs', 'roadmap.md')
  const resolvedTasksDocPath = resolve(projectRoot, configuredTasksDoc)

  if (resolvedTasksDocPath !== expectedRoadmapPath) {
    throw new Error(
      'The public generic flow requires docs/roadmap.md. ' +
      `Received ${configuredTasksDoc}. Create docs/roadmap.md and rerun bootstrap.`
    )
  }

  const scaffoldResult = await ensureGenericStarterDocs(projectRoot)

  if (!explicitTasksOverride && !scaffoldResult.created.includes('docs/roadmap.md')) {
    const confirmed = await confirmRoadmapUsage(expectedRoadmapPath)
    if (!confirmed) {
      throw new Error(
        `Bootstrap stopped. Review or replace ${expectedRoadmapPath}, then rerun bootstrap when you are ready to use that roadmap.md file.`
      )
    }
  }

  return expectedRoadmapPath
}

const profileId = inferProfileId(args)
if (profileId !== 'generic' && profileId !== 'talkstore') {
  console.error(`Unknown consumer profile "${profileId}". Expected "generic" or "talkstore".`)
  process.exit(1)
}

async function main() {
  const profile = loadProfileManifest(profileId)
  const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : new Map()
  const resolvedProjectRoot = resolve(args.project)
  const trackerFile = chooseTrackerFile(profile, resolvedProjectRoot, args.tracker)
  const tasksDoc = args.tasks || profile.docs.tasks.default_path

  if (profile.id === 'generic') {
    const roadmapPath = await validateGenericRoadmap(resolvedProjectRoot, tasksDoc, Boolean(args.tasks))
    console.log(`Detected roadmap source: ${roadmapPath}`)
    console.log('This roadmap.md file feeds the swim lane and task board.')
  }

  existing.set('COMMAND_CENTER_PROFILE', profile.id)
  existing.set('COMMAND_CENTER_PROJECT_ROOT', resolvedProjectRoot)
  existing.set('COMMAND_CENTER_TRACKER_FILE', trackerFile)
  existing.set('COMMAND_CENTER_TASKS_DOC', tasksDoc)
  const generatedKeys = [...(profile.bootstrap?.default_env_keys || [])]

  if (args.checklist || profile.id === 'talkstore') {
    existing.set('COMMAND_CENTER_CHECKLIST_DOC', args.checklist || profile.docs.checklist.default_path)
    if (!generatedKeys.includes('COMMAND_CENTER_CHECKLIST_DOC')) {
      generatedKeys.push('COMMAND_CENTER_CHECKLIST_DOC')
    }
  } else {
    existing.delete('COMMAND_CENTER_CHECKLIST_DOC')
  }

  const manifestoPath = args.manifesto || profile.docs.manifesto.default_path
  if (args.manifesto || profile.id === 'talkstore' || existsSync(join(resolvedProjectRoot, manifestoPath))) {
    existing.set('COMMAND_CENTER_MANIFESTO_DOC', manifestoPath)
    if (!generatedKeys.includes('COMMAND_CENTER_MANIFESTO_DOC')) {
      generatedKeys.push('COMMAND_CENTER_MANIFESTO_DOC')
    }
  } else {
    existing.delete('COMMAND_CENTER_MANIFESTO_DOC')
  }

  if (profile.id === 'talkstore') {
    existing.set('TALKSTORE_PROJECT_ROOT', resolvedProjectRoot)
    if (!generatedKeys.includes('TALKSTORE_PROJECT_ROOT')) {
      generatedKeys.push('TALKSTORE_PROJECT_ROOT')
    }
  } else {
    existing.delete('TALKSTORE_PROJECT_ROOT')
  }

  const lines = buildEnvLines(existing, profile, generatedKeys)

  mkdirSync(dirname(ENV_PATH), { recursive: true })
  writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')

  console.log(`Wrote ${ENV_PATH}`)
  console.log(`Consumer profile: ${existing.get('COMMAND_CENTER_PROFILE')}`)
  console.log(`Project root: ${existing.get('COMMAND_CENTER_PROJECT_ROOT')}`)
  console.log(`Tracker file: ${existing.get('COMMAND_CENTER_TRACKER_FILE')}`)
  console.log(`Tasks doc: ${existing.get('COMMAND_CENTER_TASKS_DOC')}`)
  if (existing.has('COMMAND_CENTER_CHECKLIST_DOC')) {
    console.log(`Checklist doc: ${existing.get('COMMAND_CENTER_CHECKLIST_DOC')}`)
  }
  if (existing.has('COMMAND_CENTER_MANIFESTO_DOC')) {
    console.log(`Manifesto doc: ${existing.get('COMMAND_CENTER_MANIFESTO_DOC')}`)
  }
  console.log(
    profile.id === 'talkstore'
      ? 'Compatibility: TALKSTORE_PROJECT_ROOT was written for existing TalkStore installs.'
      : 'Compatibility: no TalkStore-specific env keys were written.'
  )
  console.log('')
  console.log('Next steps:')
  if (ENV_PATH === DEFAULT_ENV_PATH) {
    console.log('1. Review the generated .env if your project uses non-default file names.')
  } else {
    console.log(`1. Review ${ENV_PATH} and move or source it for local use.`)
  }
  if (profile.id === 'generic') {
    console.log('2. Replace any starter roadmap tasks in docs/roadmap.md with your real milestone plan.')
    console.log('3. Run `npm run tracker:guard:status` before any tracker write.')
    console.log('4. Dry-run `npm run tracker:parse:project-tasks:dry-run` before any tracker write.')
    console.log('5. Write only after the dry-run looks correct with `npm run tracker:parse:project-tasks`.')
    return
  }

  console.log('2. Run `npm run tracker:guard:status` before any tracker write.')
  console.log('3. Dry-run `npm run tracker:parse:talkstore-tasks:dry-run` before any compatibility write.')
  console.log('4. Write only after the dry-run looks correct with `npm run tracker:parse:talkstore-tasks`.')
}

main().catch((error) => {
  console.error(`ERROR: ${error instanceof Error ? error.message : String(error)}`)
  process.exit(1)
})
